for item in \
  "part06-01_largest_number largest_number" \
  "part06-02_fruit_market fruit_market" \
  "part06-03_matrix matrix" \
  "part06-04_course_grading_part_1 course_grading_part_1" \
  "part06-05_course_grading_part_2 course_grading_part_2" \
  "part06-06_course_grading_part_3 course_grading_part_3" \
  "part06-07_spellchecker spellchecker" \
  "part06-08_recipe_search recipe_search" \
  "part06-09_city_bikes city_bikes" \
  "part06-10_inscription inscription" \
  "part06-11_diary diary" \
  "part06-12_filtering_file_contents filtering_file_contents" \
  "part06-13_store_personal_data store_personal_data" \
  "part06-14_course_grading_part_4 course_grading_part_4" \
  "part06-15_word_search word_search" \
  "part06-16_dictionary_file dictionary_file" \
  "part06-17_read_input read_input" \
  "part06-18_parameter_validation parameter_validation" \
  "part06-19_incorrect_lottery_numbers incorrect_lottery_numbers" \
  "part07-01_hypotenuse hypotenuse" \
  "part07-02_special_characters special_characters" \
  "part07-03_fractions fractions" \
  "part07-04_lottery_numbers lottery_numbers" \
  "part07-05_password_generator_part_1 password_generator_part_1" \
  "part07-06_password_generator_part_2 password_generator_part_2" \
  "part07-07_dice_roller dice_roller" \
  "part07-08_random_words random_words" \
  "part07-09_how_old how_old" \
  "part07-10_valid_pic valid_pic" \
  "part07-11_screen_time screen_time" \
  "part07-12_json_files json_files" \
  "part07-13_course_statistics course_statistics" \
  "part07-14_who_cheated who_cheated" \
  "part07-15_who_cheated_2 who_cheated_2" \
  "part07-16_spellchecker_2 spellchecker_2" \
  "part07-17_string_helper string_helper" \
  "part07-18_own_programming_language own_programming_language"; do
    set -- $item
    mkdir -p "$1/src" && touch "$1/src/$2.py"
done
